### ISSUE TITLE
split messaggi

### ISSUE THREAD

**Issue by toonhello** [pdpfsug/ChattaAlTesoro#11]
Prevedere la possibilità di splittare i messaggi in più messaggi consecutivi con un leggero delay.

Ad es.
### CONFIG
Eccovi! Sono felice che siate tornati. Siete pronti? Io no….ma al bando la paura! 
Iniziamo insieme questa avventura!
`---`
Abbiamo a disposizione solo quattro ore, potete controllare il tempo rimanente scrivendo /countdown.
`---`
Il primo luogo da raggiungere non è molto lontano da voi. Vi dico solo “Se lu mar è bell lu gabbian...frect!” 
Che l’avventura abbia inizio! In bocca allo scoiatt… ehm, al lupo! Conto su di voi.

### BOT
**Nomebot**: Eccovi! Sono felice che siate tornati. Siete pronti? Io no….ma al bando la paura! 
Iniziamo insieme questa avventura!

wait 5sec

**Nomebot**: Abbiamo a disposizione solo quattro ore, potete controllare il tempo rimanente scrivendo /countdown.

wait 5sec

**Nomebot**: Il primo luogo da raggiungere non è molto lontano da voi. Vi dico solo “Se lu mar è bell lu gabbian...frect!” 
Che l’avventura abbia inizio! In bocca allo scoiatt… ehm, al lupo! Conto su di voi.

**Comment by feroda** [comment]
Bisogna implementare il separatore anche nel messaggio di successo prima di chiudere questa issue
