### ISSUE TITLE
KIND emoticon o KIND open con testo emoticon

### ISSUE THREAD

**Issue by toonhello** [pdpfsug/ChattaAlTesoro#13]
E' possibile avere una domanda la cui risposta è un emoticon?

Ad es.
Codepoints
🗝 U+1F5DD U+FE0F 

https://emojipedia.org/old-key/
https://gist.github.com/endolith/157796
https://gist.githubusercontent.com/endolith/157796/raw/a37a313160a2e9d9de8d7c8151ddb9b3cc250e0d/Unicode%2520official%2520emojis.txt

**Comment by feroda** [comment]
solo da verificare secondo me se nel csv ci si mettono i caratteri dell'emoticon la rappresenta

**Comment by toonhello** [comment]
funziona inserendo via copia/incolla l'emoticon 👍
