### ISSUE TITLE
Allineare il processo di registrazione

### ISSUE THREAD

**Issue by toonhello** [pdpfsug/ChattaAlTesoro#14]
Riferimento per i dati al file di configurazione .csv condiviso (IRF_config)
Secondo foglio **iscrizione**

Nella fase di registrazione ci saranno due comandi:
- /team - Registrazione squadra
- /regolamento - Mostra il regolamento

Dateci uno sguardo al file, fatemi sapere cosa può rappresentare un problema.

**Comment by feroda** [comment]
Ok ho letto il foglio.
Quindi ci deve essere un messaggio di benvenuto allo "/start" con il bot (rel #20). 
Poi /register_team diventa /team (rel #19),
Poi bisogna implementare il comando /regolamento come scritto nel foglio
