### ISSUE TITLE
Comando /aiuto e /help per il bot di gioco

### ISSUE THREAD

**Issue by feroda** [pdpfsug/ChattaAlTesoro#17]
Servirebbe un "/help" per il bot di gioco. Un team ad esempio dovrebbe poter chiedere quanto tempo manca con /time e questo dovrebbe essere mostrato dal comanda /help o /aiuto (stesso comando)

**Comment by toonhello** [comment]
Una possibile lista di comandi potrebbe essere:

ITA
/iscrivimi - Iscrivi la tua squadra (ora register_team)
/tempo - Quanto manca alla fine della caccia al tesoro
/regolamento - Regolamento di gioco
/aiuto - Invia suggerimento (da valutare se implementare per ragioni di tempo)
