### ISSUE TITLE
Come giocatore vorrrei ricevere una risposta in caso di team non registrato

### ISSUE THREAD

**Issue by feroda** [pdpfsug/ChattaAlTesoro#6]
Per riprodurre inviare un QR code da una chat non registrata come team

**Comment by toonhello** [comment]
se possibile prevederei la possibilità di inviare un link per reindirizzare l'utente al sito di riferimento (evento, pagina dedicata, ecc.)

**Comment by feroda** [comment]
Come primo step segnaliamo la situazione all'utente con un messaggio statico, per farlo bisogna gestire i messaggi che arrivano quando il gioco è iniziato, ma il team non è presente. 

Per fare questo, data la complessità della macchina a stati della caccia al tesoro ;-) farei un if prima della valutazione di ogni "command_input" che valuta, se il gioco è iniziato e il team non è tra i team del database allora invia il messaggio che non è registrato (e qui @pharmak0n ci passi il link e lo mettiamo hardcoded), se invece il gioco non è iniziato dice di fare /regiter_team
